In [73]:
# pip install boto3[crt]

In [74]:
items

,Name,Category,description,uuid
0,801 MM Kit,Visual,,0ab85d51-7961-4f76-8870-a35caffc4ff2
1,801 Audio Kit,Audio,,63a5b29f-6579-4333-8001-8d0334ca4a3e
2,802 MM Kit,Visual,,28244dd4-458c-4beb-b2bf-58c958e350fc
3,802 Audio Kit,Audio,,bc849f67-130b-4d34-88b4-a0ce24cd1df2
4,HopeKids Ipad 1,Hopekids,,9e8c7278-51ed-4373-8af7-37b1332c91fd
...,...,...,...,...
92,Key 40: Tithing Box Key (Hopekids),NaN,,ac902e4e-c3b3-4277-abd2-139aba386a08
93,Connect 8 HK Keys,Keys,Keys,feec3d4d-2f7a-4bf3-98ed-9209630a6201
94,Connect 8 Facilities Storage,Facilities,L8 Storage Key,b1f2c143-4d0c-4d32-b322-dbd6ba73bb67
95,Extension Plug,NaN,,e877aed5-b388-4ea3-9bf6-6ae57713e9a1
96,Loud Hailer,NaN,,4ae1f106-4b43-473a-b8f3-b4393595f8a5

In [75]:
import boto3
from boto3.dynamodb.conditions import Key, Attr
import pandas as pd
import json
from decimal import Decimal
import uuid

# Get the service resource.
dynamodb = boto3.resource('dynamodb')

item_table = dynamodb.Table(
    'Item-eh4ttfc23vdd3iujr2m7mi3owq-NONE'
)

items = pd.read_csv('Items_available.csv')


items = items.drop(columns=['item_ID'])
items.rename(columns={'category':'Category'},inplace=True)

items['description'] = items['description'].fillna('')

items['id'] = [str(uuid.uuid4()) for _ in range(len(items))]

rand_uuid = uuid.uuid4()
print(rand_uuid)

# with item_table.batch_writer() as batch:
# item_table.put_item(
#         Item={
#             "id": str(rand_uuid),
#   "Name": "Sample Item",
#   "Category": "Sample Category",
#   "description": "This is a sample description."
# } 
    # )

items

efa257e3-3f63-4818-bc5f-27b17457fc4b

,Name,Category,description,id
0,801 MM Kit,Visual,,33e68beb-2579-4c9c-8a0a-0256f4d70eaa
1,801 Audio Kit,Audio,,2d3dd4fb-31d1-421f-92ad-4d1138c6db5e
2,802 MM Kit,Visual,,80076c92-0cea-4c4c-a3fc-237c0df3aab0
3,802 Audio Kit,Audio,,100af89e-c026-4369-a090-3c8507c4e124
4,HopeKids Ipad 1,Hopekids,,eaa460d2-a6a6-45e9-8d58-88b1d2fb16b5
...,...,...,...,...
92,Key 40: Tithing Box Key (Hopekids),NaN,,e34cd07c-6b35-4fe1-852c-502c762271c5
93,Connect 8 HK Keys,Keys,Keys,b42d16c4-63c2-4c02-bd7b-4fcc0bf3888b
94,Connect 8 Facilities Storage,Facilities,L8 Storage Key,638ca445-7a2c-4b17-8fcc-3256ad8070be
95,Extension Plug,NaN,,5ee84337-0462-484f-9741-5b9e7b7d58ae
96,Loud Hailer,NaN,,9a0cae49-89d3-4ba0-8b6d-0d5d83419fac

In [76]:
with item_table.batch_writer() as batch:
    for index, row in items.iterrows():
        batch.put_item(
            json.loads(row.to_json(), parse_float=Decimal)
        )

In [77]:
booking_table = dynamodb.Table('Booking-eh4ttfc23vdd3iujr2m7mi3owq-NONE')

booking_cart_table = dynamodb.Table('BookingCart-eh4ttfc23vdd3iujr2m7mi3owq-NONE')